### ISSUE TITLE
登录部分有bug

### ISSUE THREAD

**Issue by yuvast** [junqizeng/whu_emailsys#1]
mailtoolkit文件，第126行
`    def mail_login(self, acc_mail, account, author_code):
        self.client_smtp = smpt.SMTP(acc_mail, account=account, author_code=author_code)
        self.client_pop = pop3.POP3(acc_mail=acc_mail, account=account, author_code=author_code)
        smtp_login, smtp_report, smpt_socket = self.client_smtp.login_veri()
        if not smtp_login:
            return False, smtp_report
        smpt_socket.sendall(self.client_smtp.smtp_command['QUIT'])

        pop_login, pop_report, pop_socket = self.client_pop.login_veri()
        if not smtp_login:
            return False, pop_report
        pop_socket.sendall(self.client_pop.pop_command['QUIT'])

        return True, 'SMTP/POP3服务认证成功！'`
贴出来的函数第9行“if not smtp_login”错误，只有pop服务的邮箱会报错，改为"if not pop_login"可以成功运行

**Comment by junqizeng** [comment]
非常感谢，已修复
